
properties:
  width: 800
  height: 600
  paper_bgcolor: white
  plot_bgcolor: white
  plot_type: "line"

margin:
  t: 130
  b: 100
  l: 80
  r: 80

xaxis:
  showline: true
  linecolor: black
  linewidth: 2
  ticks: outside
  showgrid: false
  zeroline: true
  range: [0, 50]

yaxis:
  showline: true
  linecolor: black
  linewidth: 2
  showgrid: true
  zeroline: true
  range: [0, 100]

title:
  text: Glorious Plotly Chart
  subtitle: With a clean subtitle
  fontsize: 24
  x: 0.22
  y: 1.18
  xanchor: center
  yanchor: top

description:
  text: Proportion of survey respondents (%)
  fontsize: 14
  color: black
  x: 0.01
  y: 0.98
  xanchor: left
  yanchor: top

footnote:
  text: 'Source: Imagination, 2025'
  fontsize: 12
  color: gray
  x: 0.01
  y: -0.15
  xanchor: left
  yanchor: bottom

top-line:
  enabled: true
  color: black
  width: 2
  y: 1.02
  x0: 0
  x1: 1

legend:
  orientation: h
  x: 0.5
  y: -0.2
  xanchor: center
  yanchor: top
  bgcolor: rgba(255, 255, 255, 0.8)
  bordercolor: black
  borderwidth: 1


